chore: Initiate GSoC qualification task, fix package.json and add CSV…
json-schema-org/ecosystem pull request #10
Opened 2024-03-22 04:49 UTC by wcj617

… tests

2024-03-25 13:48 UTC, Relequestual requested changes
Welcome, and thanks for your initial work on this.
I have left a few comments and questions.


Looking at the requirements on #4.
1. Covered.
2. I have updated this to specify using the timestamp format.
3. Not covered. "Fully run" means all results without limit. There are about 1.8k results. This may take some time to run.
4. Not covered. This is important because it can take some time to run, so the script should capture errors and continue running rather than crash and exit.

When you have updated and tested, please indicate this needs to be re-reviewed. Thanks.
Feel free to reach me on our Slack under the same username if you have questions.

2024-03-25 13:48 UTC, Relequestual commented on projects/initial-data/package.json
> -    "eslint:fix": "pnpm run eslint -- --fix"
Why did you change this? =]

2024-03-25 13:48 UTC, Relequestual commented on projects/initial-data/main.js
> +    return response.data.length > 0 ? response.data[0].commit.author.date : null;
I think rather than returning null, this should error

2024-03-25 13:48 UTC, Relequestual commented on projects/initial-data/main.js
> +  return lastPageResponse.data.length > 0 ? lastPageResponse.data[0].commit.author.date : null;
I think rather than returning null, this should error

2024-03-25 21:22 UTC, wcj617 commented on projects/initial-data/.gitignore
I apologize for any confusion; I accidentally deleted the original .gitignore file but have now restored it. The project doesn't have many directories listed in the .gitignore, so the impact should be minimal.

2024-03-25 21:30 UTC, wcj617 commented on projects/initial-data/package.json
> -    "eslint:fix": "pnpm run eslint -- --fix"
Regarding the ESLint script issue, the original command eslint:fix : "pnpm run eslint -- --fix" encountered an error due to an extra -- argument. The error message was:

``
Copy code
Oops! Something went wrong! :(
ESLint: 8.54.0
No files matching the pattern "--fix" were found. Please check for typing mistakes in the pattern.
``

I've resolved this by removing the unnecessary -- option, reverting the script to a working state

2024-03-30 23:03 UTC, wcj617 commented
This is my second qualification task work!
[second qualification task.pdf](https://github.com/json-schema-org/ecosystem/files/14813532/second.qualification.task.pdf)

2024-04-04 08:35 UTC, Relequestual commented
This looks much improved. I'm scheduling some time to test it locally before it is merged. Thanks for your work on this.

2024-05-14 10:27 UTC, Relequestual requested changes
Left a few suggestions, otherwise this is looking better.

I know GSoC candidates have been selected now, but it would be nice to know if you'd like to finish this PR or not. If not, that's totally fine, and I'm sure I can find someone else to finish it or do it myself. Let me know.

2024-05-17 00:03 UTC, wcj617 commented on projects/initial-data/main.js
> +        throw new Error('No commits found'); //TODO: check if this is the correct error message
Fixed as suggested

2024-05-17 00:04 UTC, wcj617 commented on projects/initial-data/main.js
> +    throw new Error('No commits found'); //TODO: check if this is the correct error message
fixed as suggested

2024-05-17 00:04 UTC, wcj617 commented on projects/initial-data/main.js
> +        throw new Error('No releases found'); //TODO: check if this is the correct error message
fixed as suggested

2024-05-17 00:05 UTC, wcj617 commented on projects/initial-data/main.js
> +      throw new Error('No releases found'); //TODO: check if this is the correct error message
fixed as suggested

2024-05-17 00:27 UTC, wcj617 commented on projects/initial-data/main.js
> +      throw new Error('No commits found'); //TODO: check if this is the correct error message
fixed as suggested

2024-05-24 05:36 UTC, wcj617 commented
[previous git commit history]
![image](https://github.com/json-schema-org/ecosystem/assets/47830372/eb3fde69-f07b-46cf-91b9-2f03f551f80d)

[after fixed]

![2024-05-23_22-13-15](https://github.com/json-schema-org/ecosystem/assets/47830372/2836da6c-b927-41af-9ec9-364b27f5e70b)

[mock jest]
![image](https://github.com/json-schema-org/ecosystem/assets/47830372/c0e34a57-6924-440b-9088-28365b201852)

Hi Ben, 

Thank you for your insightful feedback! I appreciate the guidance and the opportunity to learn from real-world problems provided by this project.

I've completed a git rebase and resolved the divergent commits as you've noticed. I've also re-requested a review of the PR to ensure everything aligns with the project's current needs.

Regarding the API key update, your clarification was very helpful. I understand now the importance of designing tests that don't make real API calls and will take this as a key learning point.

Thank you for your support and for providing a nurturing environment for newcomers like me. I look forward to continuing my contribution to the project and will keep in touch via Slack as needed.

Best regards,
David

2024-06-18 14:17 UTC, Relequestual commented
Hey David, thanks for waiting on this. I spent a good part of the day yesterday trying to modify one of the tests to make it work correctly. I've changed approaches and should be updating this PR today.

2024-06-18 23:45 UTC, wcj617 commented
Thank you, Ben. I deeply appreciated your support:)

2024-06-21 14:23 UTC, Relequestual approved these changes

2024-06-21 14:24 UTC, merged

2024-06-21 14:25 UTC, Relequestual commented
Thanks for your work on this! Much appreciated. I made a few improvements to the testing.