Self reporting tooling schema and processes definition
json-schema-org/ecosystem pull request #12
Opened 2024-05-28 14:44 UTC by Relequestual

Related to https://github.com/json-schema-org/community/issues/412 (but does not close).
(This PR probably needs a specific Issue. Sorry.)

This PR introduces a JSON Schema which details the data structure that tooling repositories will be asked to included to self identify themselves to the JSON Schema Ecosystem project.

When the JSON Schema Ecosystem project ingests the data, it will be the Single Source of Truth for that data (beyond the source repositories). The data will then be pulled to the website repository and the landscape repository.

At this stage I'm looking for feedback and comments on the schema. I'll update with an Issue and providing a readme for tooling implementers to help them understand the expectations and what will be done with the data and why.

Work to do based on feedback:

- [x] Describe all of the tooling catagories in the readme
- [x] Specify the process for pulling in data and that it triggers a PR rather than just being accepted, as any change should be manually reviewed by a member of the JSON Schema team
- [x] Pluralize consistently
- [x] Clarify purpose of `languages` field
- [x] Require full URL of depended on validators and detail that the validator should already be known to the ecosystem repo to be accepted
- [x] Correct use of `format` to `uri`
- [x] Add field to declare support for other defined dialects
- [x] Define ingested data as automated into one file, and curated data into another file with overrides as manual with PR (created automatically)

2024-05-30 08:23 UTC, DarhkVoyd commented
@Relequestual Hello, I am currently working to prepare the new data source for the tooling page. The current data model stores tooling by categories of tooling type and sub categorises them by programming language (if applicable). I like the approach to store each tooling as a separate entity which matches this schema. This allows us to have more control over filters, sorting and other data transformations if ever required. I wanted to propose that we add some field that the tooling is language dependent (to identify toolings such as validators for a default view such as the current view) and language agnostic (for tooling such as editors and more).

2024-05-31 15:45 UTC, benjagm commented
````
  "required": [
    "name",
    "repositoryURL"
  ],
````

Regarding the required fields, name, description and toolingType should be mandatory. In addition repositoryURL should not be mandatory as some of the tooling is not opensource.

2024-06-01 12:04 UTC, DarhkVoyd commented
```
   "toolingType": {
       "description": "The category of tooling of the project",
       "type": "string",
       "enum": [
       ...
       ]
     }
```
I believe that the tooling type should be an `array` instead of a `string` as some toolings provide JSON Schema framework including validators, schema generators etc. Case: `https://www.newtonsoft.com/jsonschema`

2024-06-06 07:58 UTC, Relequestual commented
> ```
>   "required": [
>     "name",
>     "repositoryURL"
>   ],
> ```
> 
> Regarding the required fields, name, description and toolingType should be mandatory. In addition repositoryURL should not be mandatory as some of the tooling is not opensource.
> - @benjagm 

The self reporting tooling will only be tooling which has an associated repository.

We can and should track non-open source tooling here also, but we can do that later.

As discussed, we should define a roadmap of changes we will make for tooling data, and then share it publicly.

2024-06-10 16:36 UTC, Julian reviewed
Nice.

Took a first pass and left some comments with an eye on "low friction", so I've been a bit intentionally harsh, but hopefully helpful.

2024-06-10 19:42 UTC, gregsdennis requested changes
I'm not sure that we should be leaving some of this information to the creators of the projects.  I think such a system can be easily abused, and we would need to have checks for that.

For example, the `compliance` field:  can we really trust maintainers to admit that their libraries aren't 100% compliant by default?  We already know of at least one that doesn't.

I'm not sure that I agree that this is the right direction.  I like the automation aspect, but I still think that the tooling list is something that needs to be curated by a trusted source (someone directly associated with our org).

2024-06-11 08:07 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +          "linter-plugins"
I think the reference suite would be a testing utility (`util-testing`) and Bowtie would be both that and a `validator` with a long list of `dependsOnValidators`.

I think Bowtie is special and we're unlikely to see more tools of the same class (a federated-validator? Although you could argue that the vision I have for my playground or indeed any validator which supports multiple underlying validators COULD be in that class.)

2024-06-11 08:09 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +        "type": "string"
Seems obvious now you say it, especially given I was looking at the naming approach of Bowtie 🤦‍♂️. Thanks.

2024-06-11 08:11 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +      "description": "The platforms or environments in which the tool or library is designed to operate. This field is optional and should be included when the tool or library is specific to a certai
I thought about this and was chatting with some people on this. We COULD include OS here, but I don't feel like most maintainers will fill in this info, or even care about such things.
You usually expect if the language runs on your OS, then so does the library you want to use. Is there something else to this that I'm missing?

2024-06-11 08:14 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +    "creators": {
What's your thinking behind this?

I was thinking it may not be clear or it may not be known. Such as if a company decides to open source an implementation it owns, but can't accuratly ascibe an individual as having created it.

2024-06-11 08:15 UTC, Julian commented on projects/tooling-self-identification/identification.schema.json
> +          "linter-plugins"
Sounds reasonable (on both), thanks!

2024-06-11 08:19 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +    "homepageURL": {
I did look at it while creating this, but I'll make some adjustments to align at this point.

2024-06-11 08:24 UTC, Julian commented on projects/tooling-self-identification/identification.schema.json
> +    "creators": {
I didn't think too hard for this comment so possibly it's ignorable. I was commenting based on knowing on PyPI (pypi.org) and most package indices I know of that it's always required to have at least one person listed, no matter what. But for our use case I guess yeah probably not needed.

2024-06-11 08:26 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +      "description": "A date in the format of YYYY-MM-DD which repersents when the document was last updated.",
We used to include this on the website, but we don't anymore, and I'm not sure how useful it is in truth. And you're right, we can. On the odd occasion it may be inaccurate if a file is just moved or whitespace is fixed, but I think you're right, we can't expect people to update this.

I think we used it in the website data for our own reference mostly.

2024-06-11 09:14 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +                "C#",
Intersting. I do not know this space and so did wonder.
However, I note that Quicktype, a web based UI for code generation (and other things) specifically lists C# as something they support.

For "what validator can I use?", I'd agree with you (based on what I know). But in terms of "what languages can I convert to/from?", I feel like knowing specifically about C# makes sense, right?

2024-06-11 10:14 UTC, Julian commented on projects/tooling-self-identification/identification.schema.json
> +                "C#",
Just because I almost left a similar comment myself before noticing this field was plural -- @gregsdennis in case you missed it note that this field allows you to declare *multiple* languages.

2024-06-11 13:41 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +      "enum": [
It is true that PyPi classifiers are far more used, but I don't see any other package manager file format looking to specify project status. And, I'm not sure it's really talking about project maturity either. If a project is classified as a "toy", you might never use it in production, because the author is signalling they don't intend to really maintain it. It may very well be stable, but it might not be getting security patches.

I'm not expecting maintainers to go look at this schema.
Considering that, what probably makes senes is to provide a template for maintainers to use which is just the minimal, and invite those who have time or are curious to look at the optional fields, such as this one.

I think maturity is actually pretty interesting and something we could consider adding!

Do you know where I can find the definitions of the Development Status classifier levels used by PyPi?

2024-06-11 14:01 UTC, Julian commented on projects/tooling-self-identification/identification.schema.json
> +      "enum": [
Actually I wasn't even specifically referring to PyPI classifiers when commenting previously. I was *assuming* that this scale is about project maturity. Though now spending 30 seconds instead of 3 I see it's not about that at all. But given I haven't spent much more than that, I don't really know why it's useful to say something is a `toy` vs saying it is `alpha` maturity. To someone encountering the project they presumably should take the same "practical" information out of seeing that. Which again kind of leaves me saying "cute, someone has some simple model of how to classify projects" but not as an implementer "oh god I need to take the time to see what this is so I can fill this out".

But! I did not notice it's optional, so if it is, then all the above is irrelevant probably, and indeed people will ignore it if they don't know what it is.

2024-06-12 10:44 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +      "type": "string"
I've noted we will use an existing source of information if available.

2024-06-12 10:45 UTC, Relequestual commented on projects/tooling-self-identification/readme.md
> +- Repository has the Topic `json-schema` assigned
I've updated the schema structure and noted in the readme that while initial support will be only for GitHub, we will work to use other sources as soon as we can.

2024-06-12 12:28 UTC, Relequestual commented
> I'm not sure that we should be leaving some of this information to the creators of the projects. I think such a system can be easily abused, and we would need to have checks for that.

Agreed. We can make it so the automation creates a PR for us to review, rather than blanket acceptance.

> For example, the `compliance` field: can we really trust maintainers to admit that their libraries aren't 100% compliant by default? We already know of at least one that doesn't.

Not always, no. But, I count SIX implementations where we said that they document what must be done to be fully to the specification compliant. Some libraries are written in specific contexts where they don't want that by default, I guess.
If we include the field, some more may add such details if they exist.

> I'm not sure that I agree that this is the right direction. I like the automation aspect, but I still think that the tooling list is something that needs to be curated by a trusted source (someone directly associated with our org).

Agreed. We can make it so the automation creates a PR. We need to do this anyway really, because someone could put ANYTHING there. If an implementation repo was compromised, they could add undesierable content.

2024-06-13 05:14 UTC, Julian commented on projects/tooling-self-identification/identification.schema.json
> +  "$defs": {
Minor schema style so feel free to ignore, but I'd generally put this (`$defs` in general in fact) at the bottom personally, the same way that in some code, if I have "important function X" and "helper function Y", the helper function gets put at the bottom, so that someone reading sees X first, which is usually all they need to know about until/unless they care about implementation details.

2024-06-13 05:15 UTC, Julian commented on projects/tooling-self-identification/identification.schema.json
> +    "toolingType": {
You have `toolingType` here even though it's an array, but you have `languages` (plural) below. Possibly good to be consistent there on whether naming properties in plural or not.

2024-06-13 05:17 UTC, Julian commented on projects/tooling-self-identification/identification.schema.json
> +                "OpenAPI",
OpenAPI is a language?

2024-06-13 05:17 UTC, Julian commented on projects/tooling-self-identification/identification.schema.json
> +            "description": "A string value not yet included in the list of envrionments"
```suggestion
            "description": "A string value not yet included in the list of environments"
```

2024-06-13 05:18 UTC, Julian commented on projects/tooling-self-identification/identification.schema.json
> +    "dependsOnValidators": {
Since it seems like we're specifically targeting all types of tools with this, any reason to name the property `dependsOn*Validators*`? Rather than just `dependsOnTools` or even simply `dependsOn`?

2024-06-13 05:20 UTC, Julian commented on projects/tooling-self-identification/identification.schema.json
> +        "$comment": "In the case where it's known that there are implementations with the same name in different programming languages, please use the repository or source URL.",
I wouldn't leave this up to someone personally, if there's one unique tool called `foo` today, and then next year someone adds a second one with the same name in some other random language, no one with `foo` in their list will 1) realize and 2) go back and change their `foo` to be more specific I don't think.

2024-06-13 05:21 UTC, Julian commented on projects/tooling-self-identification/identification.schema.json
> +      "format": "URL"
The format is called `uri`, assuming you're trying to use the one from the spec.

2024-06-13 05:22 UTC, Julian commented on projects/tooling-self-identification/identification.schema.json
> +      "additionalProperties": false
Perhaps it's a conscious choice, but you're disallowing someone declaring they support some *unofficial* dialect here obviously.

2024-06-13 05:25 UTC, Julian approved these changes
Left another round of comments, but after addressing whichever of those suit you, lgtm.

2024-06-13 06:45 UTC, gregsdennis reviewed
I'm interested in how the override is expected to work.  What happens when the maintainer updates an overridden field?

I think it's important to explicitly state that this is data mining and that we will still be curating the end results of the website and landscape.

2024-06-13 06:45 UTC, gregsdennis commented on projects/tooling-self-identification/readme.md
> +This project aims to enable tooling authors and maintainers to detail their tools existence and additional information to be listed on the JSON Schema website and Landscape diagram.
```suggestion
This project aims to enable tooling authors and maintainers to detail their tools' existence and additional information to be listed on the JSON Schema website and Landscape diagram.
```

Should be possessive, and a maintainer could have multiple tools.

2024-06-13 06:45 UTC, gregsdennis commented on projects/tooling-self-identification/readme.md
> +The approach is to define a data structure for a file which is located in their own repo, which will then be located and extracted into a single file within this repository. Other repositories such a
```suggestion
The approach is to define a data structure for a file hosted located in their own repo, which will then be located and extracted into a single file within this repository. Other repositories such as the website and landscape repositories, will then copy and transform the data as required. The data may be used to augment or totally replace the data they hold, if any.
```

I think maybe just do a read through and see how many "which"'s there are...

2024-06-13 06:45 UTC, gregsdennis commented on projects/tooling-self-identification/identification.schema.json
> +  "$defs": {
Interesting.  I typically put it up front for the same reason.

I learned programming primarily in C, in which the compiler reads from start to finish, so symbols have to be declared (but maybe not defined) before they're used.  This likely shaped how I think of ordering.

I still do it in other areas, but I've also noticed that it doesn't align with some things.  For example, in C#'s "[Top Level Statements](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements)" feature, any classes that need to be created MUST be at the bottom of the file, after an explicit `return`.  This is weird for me because I keep wanting to put them at the top.

2024-06-13 07:20 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +  "$defs": {
Interesting indeed! I generally put or move it to the top.
I see your argument for code though.

2024-06-13 07:22 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +                "OpenAPI",
It's a thing that some tools support translating from/to. It wouldn't be in the list of languages a validator supports.

I'm not convinced it's a platform. Maybe a "format" would be better for those classifications?

2024-06-13 07:23 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +            "description": "A string value not yet included in the list of envrionments"
I ran it through spell checking this time too... 😅

2024-06-13 07:43 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +    "dependsOnValidators": {
It

2024-06-13 07:53 UTC, Julian commented on projects/tooling-self-identification/identification.schema.json
> +                "OpenAPI",
Ah ok I understood this field to mostly be used for "language this is written in and therefore most easily usable from".

2024-06-13 08:16 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +        "$comment": "In the case where it's known that there are implementations with the same name in different programming languages, please use the repository or source URL.",
You're right, and I'm not sure what to do about this except always require the source URL only.
Then, either there are two options. One, do processing against the source to determine the name. Or two, only allow source URLs which are already known in the existing data (which may include the "legacy" data). This then avoids having to use any third party services to determine the name. (Because it would be more complicated the more services which were supported.)

2024-06-13 08:36 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +      "additionalProperties": false
It wasn't, and that's a good point.
I had a little think on this. Obviously we want people to be able to easily find validators that support the standard/official dialects, but there are plenty of tools which support OpenAPI[Version] for example.

I'll add an extra field for additional dialects.

2024-06-13 08:36 UTC, Relequestual commented
> I'm okay with this as a data mining effort, but not as a relay directly to our sites. This data should be curated before it's published in any form. - @gregsdennis 

The readme states that the process will create a PR into this repo and not just mine the data. So it will be curated.

> Data that's collected when it meets the above stated criteria will be used to create a Pull Request into the ecosystem repo to add or update the information.

Is this enough? Did you maybe miss this?

If we don't use this data for the website and landscape, we're loosing a LOT of the value from doing this work in the first place.

2024-06-13 08:52 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +          "validator",
This is now done in the readme.

2024-06-13 08:56 UTC, Relequestual commented on projects/tooling-self-identification/identification.schema.json
> +                "OpenAPI",
It is, but it took on a dual purpose.
For validators, yes, it represents the language it is written in.
For other tools, it represents the languages (or formats) it supports.
I could make this clearer in the description.

2024-06-13 09:02 UTC, gregsdennis commented
Yeah, posting that comment was more to make it public rather than something we just discussed in private. I'm aware that we'll have an opportunity to review a PR before anything goes in. 

I was thinking data ingestion would be purely automatic.  Then separately we'd have a curation step where the curated data is a new file (and included any overrides/changes we wanted).

Instead, you've chosen to have ingestion and curation together, but we also have overrides as a separate file.  It's just a different way to do it.  Also, I suppose the curation part would allow us to just decline to add something, but we'd need some way of tracking that we declined it or the bot will keep finding it.

2024-06-13 09:04 UTC, Relequestual commented on projects/tooling-self-identification/readme.md
> +The approach is to define a data structure for a file which is located in their own repo, which will then be located and extracted into a single file within this repository. Other repositories such a
Can you explain this please? It feels like you're assuming it should be obvious why this is bad? Does it make it harder to read or understand?

The primary purpose of the readme is to explain things. It often goes into more detail about things.
I'm open to more specific suggestions if you have them.

2024-06-13 14:27 UTC, Relequestual commented
You know, I can easily think of several reasons why we would actually want to have a seperate ingestion file vs curated file. So, let me amend the readme.

For example, it would be helpful to keep ingestion events logged in a file which can then be used to more easily make time series graphs.

> ...we'd need some way of tracking that we declined it or the bot will keep finding it.
Even with ingestion being automated and copying to the curated data being manual, it could be beneficial to know if an updated entry was rejected before, and why.

2024-06-14 12:26 UTC, DarhkVoyd approved these changes

2024-06-17 10:37 UTC, Relequestual commented
🙏 Huge thanks for all your feedback on this work!
I'm convinced this is going to be the start of elevating the ecosystem to the next level.

2024-06-17 10:37 UTC, merged